version: "2.0"

language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  transformer_size: 512
  ranking_length: 5
  constrain_similarities: True
  model_confidence: "linear_norm"
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 10
  batch_size:
  - 16
  - 32
  number_of_transformer_layers: 2
  transformer_size: 1024
  constrain_similarities: True
  model_confidence: "linear_norm"
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: "RasaCustomPolicies.NLUFallbackPolicy"
  priority: 6
  nlu_threshold: 0.25
  ambiguity_threshold: 0.15
  fallback_action_name: 'action_not_understand_fallback'
- name: "RasaCustomPolicies.PredictionFallbackPolicy"
  priority: 4
  core_threshold: 0.5
  fallback_action_name: 'action_not_sure_what_to_do_fallback'
