language: en
pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  transformer_size: 512
  ranking_length: 5
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  max_history: 3
  epochs: 10
  batch_size:
  - 32
  - 64
  number_of_transformer_layers: 3
  transformer_size: 512
- name: AugmentedMemoizationPolicy
  max_history: 3
- name: "RasaCustomPolicies.NLUFallbackPolicy"
  priority: 6
  nlu_threshold: 0.5
  ambiguity_threshold: 0.3
  fallback_action_name: 'action_not_understand_fallback'
- name: "RasaCustomPolicies.PredictionFallbackPolicy"
  priority: 4
  core_threshold: 0.35
  fallback_action_name: 'action_not_sure_what_to_do_fallback'
