language: en
pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  ranking_length: 5
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 64
  - 128
- max_history: 12
  name: AugmentedMemoizationPolicy
- name: MappingPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.9
  ambiguity_threshold: 0.1
  core_threshold: 0.7
  fallback_action_name: 'action_not_understand_fallback'
